const data = {
  product: [
    {
      id: 1,
      slug: 'slim-shirt',
      name: ' Slim-shirt',
      catagary: 'Shirt',
      img: '/images/2.jpg',
      price: 3000,
      barnd: 'Nike',
      rating: 4.6,
      numreviews: 10,
      Discription: 'high Qulity',
    },
    {
      id: 2,
      slug: 'Adidass-slim-shirt',
      name: 'Adidas Slim-shirt',
      catagary: 'Shirt',
      img: '/images/3.jpg',
      price: 3000,
      barnd: 'Adidas',
      rating: 4.6,
      numreviews: 10,
      Discription: 'high Qulity',
    },
    {
      id: 3,
      slug: 'slim-pants',
      name: ' Slim-pants',
      catagary: 'pants',
      img: '/images/1.jpg',
      price: 3000,
      barnd: 'Nike',
      rating: 4.6,
      numreviews: 10,
      Discription: 'high Qulity',
    },
  ],
};
export default data;
